-- ============================================================
-- Migration: Expand artist category seed list
-- Apply this in Supabase or via your migration workflow
-- ============================================================

insert into categories (name) values
  ('Singer'),
  ('Bollywood Singer'),
  ('Wedding Singer'),
  ('Devotional Singer'),
  ('Live Musician'),
  ('Band'),
  ('Live Band'),
  ('Acoustic Duo'),
  ('DJ'),
  ('Comedian'),
  ('Magician'),
  ('Mentalist'),
  ('Dancer'),
  ('Bharatanatyam Dancer'),
  ('Bhangra Dancer'),
  ('Hip Hop Dancer'),
  ('Contemporary Dancer'),
  ('Belly Dancer'),
  ('Choreographer'),
  ('Emcee / Host'),
  ('Anchor'),
  ('Photographer'),
  ('Drone Photographer'),
  ('Videographer'),
  ('Makeup Artist'),
  ('Beauty Parlour / Salon'),
  ('Hair Stylist'),
  ('Nail Artist'),
  ('Mehendi Artist'),
  ('Bridal Mehendi Artist'),
  ('Tattoo Artist'),
  ('Event Decorator'),
  ('Event Planner'),
  ('Guitarist'),
  ('Keyboardist'),
  ('Drummer'),
  ('Percussionist'),
  ('Saxophonist'),
  ('Violinist'),
  ('Flutist'),
  ('Tabla Player'),
  ('Qawwali Singer'),
  ('Folk Singer'),
  ('Classical Singer'),
  ('Kids Entertainer'),
  ('Storyteller'),
  ('Caricature Artist'),
  ('Face Painter'),
  ('Balloon Artist'),
  ('Celebrity Appearance'),
  ('Puppet Show Artist'),
  ('Other')
on conflict (name) do nothing;
